import {
  type Genre,
  GenreSchema,
  type StreamingService,
  StreamingServiceSchema,
  type Title,
  TitleSchema,
} from '@flixy/shared';

const observedAt = '2026-01-01T00:00:00.000Z';

const serviceRows = [
  {
    id: 'netflix',
    name: 'Netflix',
    logoUrl: null,
    regions: ['US', 'TR', 'BG', 'ES', 'DE', 'FR', 'BR'],
    displayRank: 10,
  },
  {
    id: 'prime_video',
    name: 'Prime Video',
    logoUrl: null,
    regions: ['US', 'TR', 'BG', 'ES', 'DE', 'FR', 'BR'],
    displayRank: 20,
  },
  {
    id: 'disney_plus',
    name: 'Disney+',
    logoUrl: null,
    regions: ['US', 'TR', 'BG', 'ES', 'DE', 'FR', 'BR'],
    displayRank: 30,
  },
  {
    id: 'hbo_max',
    name: 'Max',
    logoUrl: null,
    regions: ['US', 'ES', 'DE', 'FR', 'BR'],
    displayRank: 40,
  },
  {
    id: 'apple_tv',
    name: 'Apple TV+',
    logoUrl: null,
    regions: ['US', 'TR', 'BG', 'ES', 'DE', 'FR', 'BR'],
    displayRank: 50,
  },
  { id: 'hulu', name: 'Hulu', logoUrl: null, regions: ['US'], displayRank: 60 },
  {
    id: 'mubi',
    name: 'MUBI',
    logoUrl: null,
    regions: ['US', 'TR', 'BG', 'ES', 'DE', 'FR', 'BR'],
    displayRank: 110,
  },
] satisfies StreamingService[];

export const FALLBACK_STREAMING_SERVICES = serviceRows.map((s) => StreamingServiceSchema.parse(s));

export const FALLBACK_GENRES = [
  { id: 'action', displayRank: 10 },
  { id: 'adventure', displayRank: 20 },
  { id: 'animation', displayRank: 30 },
  { id: 'comedy', displayRank: 40 },
  { id: 'crime', displayRank: 50 },
  { id: 'documentary', displayRank: 60 },
  { id: 'drama', displayRank: 70 },
  { id: 'family', displayRank: 80 },
  { id: 'fantasy', displayRank: 90 },
  { id: 'history', displayRank: 100 },
  { id: 'horror', displayRank: 110 },
  { id: 'mystery', displayRank: 120 },
  { id: 'romance', displayRank: 130 },
  { id: 'sci_fi', displayRank: 140 },
  { id: 'thriller', displayRank: 150 },
] satisfies Genre[];

export const FALLBACK_GENRES_PARSED = FALLBACK_GENRES.map((g) => GenreSchema.parse(g));

const serviceNameById = new Map(FALLBACK_STREAMING_SERVICES.map((s) => [s.id, s.name]));
const serviceIdByName = new Map(
  FALLBACK_STREAMING_SERVICES.map((s) => [s.name.toLowerCase(), s.id]),
);

export function normalizeServiceId(value: string): string {
  const direct = serviceNameById.has(value) ? value : null;
  if (direct) return direct;
  const byName = serviceIdByName.get(value.toLowerCase());
  if (byName) return byName;
  return value
    .trim()
    .toLowerCase()
    .replace(/\+/g, '_plus')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

export function normalizeGenreId(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/sci[-\s]?fi/g, 'sci_fi')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function availability(
  serviceId: string,
  region: string,
  offerType: 'subscription' | 'rent' | 'buy' | 'free' = 'subscription',
) {
  return { serviceId, region, offerType, deepLink: null, observedAt };
}

export const FALLBACK_TITLES: Title[] = TitleSchema.array().parse([
  {
    id: '11111111-1111-4111-8111-111111111111',
    tmdbId: 155,
    kind: 'movie',
    title: 'The Dark Knight',
    originalTitle: 'The Dark Knight',
    overview:
      'A vigilante faces a chaotic criminal mastermind while Gotham decides what justice costs.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2008,
    runtimeMinutes: 152,
    imdbRating: 9.0,
    popularity: 980,
    genres: ['action', 'crime', 'thriller'],
    language: 'en',
    availability: [availability('hbo_max', 'US'), availability('netflix', 'TR')],
  },
  {
    id: '22222222-2222-4222-8222-222222222222',
    tmdbId: 27205,
    kind: 'movie',
    title: 'Inception',
    originalTitle: 'Inception',
    overview:
      'A thief steals secrets through dream-sharing technology and takes one last impossible job.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2010,
    runtimeMinutes: 148,
    imdbRating: 8.8,
    popularity: 950,
    genres: ['action', 'sci_fi', 'thriller'],
    language: 'en',
    availability: [availability('netflix', 'TR'), availability('prime_video', 'US', 'rent')],
  },
  {
    id: '33333333-3333-4333-8333-333333333333',
    tmdbId: 157336,
    kind: 'movie',
    title: 'Interstellar',
    originalTitle: 'Interstellar',
    overview: 'Explorers travel through a wormhole to find a future for humanity.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2014,
    runtimeMinutes: 169,
    imdbRating: 8.7,
    popularity: 920,
    genres: ['adventure', 'drama', 'sci_fi'],
    language: 'en',
    availability: [
      availability('prime_video', 'US', 'rent'),
      availability('apple_tv', 'US', 'buy'),
    ],
  },
  {
    id: '44444444-4444-4444-8444-444444444444',
    tmdbId: 550,
    kind: 'movie',
    title: 'Fight Club',
    originalTitle: 'Fight Club',
    overview:
      'An insomniac office worker forms an underground fight club that becomes something larger.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 1999,
    runtimeMinutes: 139,
    imdbRating: 8.8,
    popularity: 870,
    genres: ['drama', 'thriller'],
    language: 'en',
    availability: [availability('netflix', 'US'), availability('netflix', 'TR')],
  },
  {
    id: '55555555-5555-4555-8555-555555555555',
    tmdbId: 680,
    kind: 'movie',
    title: 'Pulp Fiction',
    originalTitle: 'Pulp Fiction',
    overview:
      'Two hitmen, a boxer, and a gangster couple collide across one volatile Los Angeles day.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 1994,
    runtimeMinutes: 154,
    imdbRating: 8.9,
    popularity: 850,
    genres: ['crime', 'drama'],
    language: 'en',
    availability: [availability('netflix', 'US'), availability('mubi', 'US')],
  },
  {
    id: '66666666-6666-4666-8666-666666666666',
    tmdbId: 13,
    kind: 'movie',
    title: 'Forrest Gump',
    originalTitle: 'Forrest Gump',
    overview: 'Decades of American history unfold through the eyes of a kind Alabama man.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 1994,
    runtimeMinutes: 142,
    imdbRating: 8.8,
    popularity: 800,
    genres: ['comedy', 'drama', 'romance'],
    language: 'en',
    availability: [availability('prime_video', 'US'), availability('apple_tv', 'US', 'buy')],
  },
  {
    id: '12121212-1212-4122-8122-121212121212',
    tmdbId: 424,
    kind: 'movie',
    title: "Schindler's List",
    originalTitle: "Schindler's List",
    overview: 'A businessman saves Jewish refugees during World War II.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 1993,
    runtimeMinutes: 195,
    imdbRating: 8.9,
    popularity: 780,
    genres: ['drama', 'history'],
    language: 'en',
    availability: [availability('mubi', 'US'), availability('apple_tv', 'US', 'buy')],
  },
  {
    id: '77777777-7777-4777-8777-777777777777',
    tmdbId: 12,
    kind: 'movie',
    title: 'Finding Nemo',
    originalTitle: 'Finding Nemo',
    overview: 'A cautious clownfish crosses the ocean to find his abducted son.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2003,
    runtimeMinutes: 100,
    imdbRating: 8.2,
    popularity: 770,
    genres: ['animation', 'adventure', 'family'],
    language: 'en',
    availability: [availability('disney_plus', 'US'), availability('prime_video', 'US')],
  },
  {
    id: '13131313-1313-4133-8133-131313131313',
    tmdbId: 122,
    kind: 'movie',
    title: 'The Lord of the Rings: The Return of the King',
    originalTitle: 'The Lord of the Rings: The Return of the King',
    overview: 'Frodo and Sam reach Mordor as the final battle for Middle-earth begins.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2003,
    runtimeMinutes: 201,
    imdbRating: 8.9,
    popularity: 820,
    genres: ['adventure', 'fantasy'],
    language: 'en',
    availability: [availability('prime_video', 'US', 'rent'), availability('hbo_max', 'US')],
  },
  {
    id: '88888888-8888-4888-8888-888888888888',
    tmdbId: 603,
    kind: 'movie',
    title: 'The Matrix',
    originalTitle: 'The Matrix',
    overview:
      'A hacker discovers reality is a simulation and joins a rebellion against its architects.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 1999,
    runtimeMinutes: 136,
    imdbRating: 8.7,
    popularity: 880,
    genres: ['action', 'sci_fi'],
    language: 'en',
    availability: [availability('hbo_max', 'US'), availability('mubi', 'US')],
  },
  {
    id: '99999999-9999-4999-8999-999999999999',
    tmdbId: 1399,
    kind: 'tv',
    title: 'Game of Thrones',
    originalTitle: 'Game of Thrones',
    overview: 'Noble families wage war for the Iron Throne while an older threat returns.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2011,
    runtimeMinutes: 60,
    contentRating: 'TV-MA',
    imdbRating: 9.2,
    criticScore: null,
    popularity: 990,
    genres: ['drama', 'fantasy', 'adventure'],
    language: 'en',
    tagline: null,
    directors: [],
    creators: ['David Benioff', 'D. B. Weiss'],
    cast: ['Emilia Clarke', 'Kit Harington', 'Peter Dinklage', 'Lena Headey'],
    availability: [availability('hbo_max', 'US')],
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    tmdbId: 1396,
    kind: 'tv',
    title: 'Breaking Bad',
    originalTitle: 'Breaking Bad',
    overview: 'A chemistry teacher becomes a meth producer after a terminal diagnosis.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2008,
    runtimeMinutes: 49,
    imdbRating: 9.5,
    popularity: 970,
    genres: ['crime', 'drama', 'thriller'],
    language: 'en',
    availability: [availability('hbo_max', 'US'), availability('netflix', 'US', 'rent')],
  },
  {
    id: '14141414-1414-4144-8144-141414141414',
    tmdbId: 1668,
    kind: 'tv',
    title: 'Friends',
    originalTitle: 'Friends',
    overview: 'Six twenty-somethings in Manhattan navigate friendship, work, and romance.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 1994,
    runtimeMinutes: 22,
    imdbRating: 8.9,
    popularity: 760,
    genres: ['comedy', 'romance'],
    language: 'en',
    availability: [availability('netflix', 'US', 'rent'), availability('hbo_max', 'US')],
  },
  {
    id: '17171717-1717-4177-8177-171717171717',
    tmdbId: 1100,
    kind: 'tv',
    title: 'How I Met Your Mother',
    originalTitle: 'How I Met Your Mother',
    overview:
      'Ted Mosby tells his children the long story of how he met their mother, with every friendship, heartbreak, and bad idea along the way.',
    posterUrl: null,
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2005,
    runtimeMinutes: 22,
    contentRating: 'TV-14',
    imdbRating: 8.3,
    criticScore: null,
    popularity: 765,
    genres: ['comedy', 'romance'],
    language: 'en',
    tagline: null,
    directors: [],
    creators: ['Carter Bays', 'Craig Thomas'],
    cast: ['Josh Radnor', 'Jason Segel', 'Cobie Smulders', 'Neil Patrick Harris'],
    availability: [availability('hulu', 'US'), availability('prime_video', 'US', 'rent')],
  },
  {
    id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    tmdbId: 66732,
    kind: 'tv',
    title: 'Stranger Things',
    originalTitle: 'Stranger Things',
    overview: 'Kids in 1980s Indiana face supernatural mysteries and a secretive lab.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2016,
    runtimeMinutes: 51,
    imdbRating: 8.7,
    popularity: 940,
    genres: ['drama', 'fantasy', 'sci_fi'],
    language: 'en',
    availability: [availability('netflix', 'US'), availability('netflix', 'TR')],
  },
  {
    id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    tmdbId: 60059,
    kind: 'tv',
    title: 'Better Call Saul',
    originalTitle: 'Better Call Saul',
    overview: 'A small-time lawyer slowly becomes the criminal attorney Saul Goodman.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2015,
    runtimeMinutes: 46,
    imdbRating: 8.9,
    popularity: 700,
    genres: ['crime', 'drama'],
    language: 'en',
    availability: [availability('hbo_max', 'US'), availability('netflix', 'US', 'rent')],
  },
  {
    id: '15151515-1515-4155-8155-151515151515',
    tmdbId: 1402,
    kind: 'tv',
    title: 'The Walking Dead',
    originalTitle: 'The Walking Dead',
    overview: 'Survivors navigate a post-apocalyptic world overrun by zombies.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/n4znNs4Yz4QO7M1yUzRsNTSHSqZ.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2010,
    runtimeMinutes: 44,
    imdbRating: 8.1,
    popularity: 720,
    genres: ['drama', 'horror', 'thriller'],
    language: 'en',
    availability: [
      availability('netflix', 'US', 'rent'),
      availability('prime_video', 'US', 'rent'),
    ],
  },
  {
    id: 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',
    tmdbId: 94997,
    kind: 'tv',
    title: 'House of the Dragon',
    originalTitle: 'House of the Dragon',
    overview: 'The Targaryen civil war begins two centuries before Game of Thrones.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2022,
    runtimeMinutes: 60,
    imdbRating: 8.5,
    popularity: 930,
    genres: ['drama', 'fantasy'],
    language: 'en',
    availability: [availability('hbo_max', 'US')],
  },
  {
    id: '16161616-1616-4166-8166-161616161616',
    tmdbId: 84958,
    kind: 'tv',
    title: 'Loki',
    originalTitle: 'Loki',
    overview: 'The mischievous trickster god is pulled into a time-bending TVA mission.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/voHUmluYmKyleFkTu3lOXQG702u.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2021,
    runtimeMinutes: 50,
    imdbRating: 8.2,
    popularity: 650,
    genres: ['action', 'adventure', 'fantasy'],
    language: 'en',
    availability: [availability('disney_plus', 'US'), availability('disney_plus', 'BR')],
  },
  {
    id: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
    tmdbId: 60625,
    kind: 'tv',
    title: 'Rick and Morty',
    originalTitle: 'Rick and Morty',
    overview: 'A scientist and his grandson ricochet through reckless intergalactic adventures.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/gdIrmf2DdY5mgN6ycVP0XlzKzbE.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2013,
    runtimeMinutes: 22,
    imdbRating: 9.1,
    popularity: 690,
    genres: ['animation', 'comedy', 'sci_fi'],
    language: 'en',
    availability: [availability('netflix', 'US'), availability('netflix', 'TR')],
  },
  {
    id: 'ffffffff-ffff-4fff-8fff-ffffffffffff',
    tmdbId: 76479,
    kind: 'tv',
    title: 'The Boys',
    originalTitle: 'The Boys',
    overview:
      'Vigilantes take on superheroes who abuse celebrity, power, and corporate protection.',
    posterUrl: 'https://image.tmdb.org/t/p/w780/stTEycfG9928HYGEISBFaG1ngjM.jpg',
    backdropUrl: null,
    trailerKey: null,
    releaseYear: 2019,
    runtimeMinutes: 60,
    imdbRating: 8.7,
    popularity: 880,
    genres: ['action', 'crime', 'sci_fi'],
    language: 'en',
    availability: [availability('prime_video', 'US'), availability('netflix', 'US', 'rent')],
  },
]);
